import { styled } from "../../stitches.config";
import Head from "next/head";
import { SideNavBar } from "../SideNav/SideNav";
type MainProps = {
  children: JSX.Element;
};

const ContentContiner = styled("main", {
  display: "flex",
  backgroundColor: "$mauve3",
  overflowX: "hidden",
  minHeight: "100vh",
});

const Page = styled("div", {
  marginLeft: "266px",
  marginTop: "$3",
  marginBottom: "$3",
  marginRight: "$3",
  borderRadius: " $3",
  padding: "$4",
  display: "flex",
  flexDirection: "column",
  width: "100%",
  backgroundColor: "$background-primary-neutral",
  boxShadow: "0px 1px 2px $colors$shadow-default",
  border: "1px solid $colors$mauve4",
  alignItems: "center",
  overflowY: "scroll",
  height: "calc(100vh - 76px)",
});

const Container = styled("div", {
  display: "flex",
  flexDirection: "column",
  marginTop: "64px",
  marginLeft: "auto",
  marginRight: "auto",
  width: "100%",
  variants: {
    width: {
      phone: { maxWidth: "300px" },
      tablet: { maxWidth: "480px" },
      desktop: { maxWidth: "820px" },
      monitor: { maxWidth: "1080px" },
      default: { maxWidth: "820px" },
    },
  },
});
export default function MainLayout({ children }: MainProps) {
  return (
    <div>
      <Head>
        <title>Alloy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ContentContiner>
        <SideNavBar />
        <Page>
          <Container
            width={{
              "@initial": "default",
              "@phone": "phone",
              "@tablet": "tablet",
              "@desktop": "desktop",
              "@monitor": "monitor",
            }}
          >
            {children}
          </Container>
        </Page>
      </ContentContiner>
    </div>
  );
}
